# Generated by Django 4.2.2 on 2023-06-22 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComprasContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_time', models.BigIntegerField()),
                ('id_processo', models.BigIntegerField()),
                ('id_orgao_contrato', models.BigIntegerField()),
                ('id_contrato', models.BigIntegerField()),
                ('id_contratado', models.BigIntegerField()),
                ('situacao_cont', models.BigIntegerField()),
                ('ano_particao', models.BigIntegerField()),
                ('vr_homologado', models.FloatField()),
                ('vr_atualizado', models.FloatField()),
            ],
            options={
                'db_table': 'ComprasContrato',
            },
        ),
        migrations.DeleteModel(
            name='Cadastro',
        ),
    ]
